import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://rolety.aliplast.pl/Account/Login');
  await page.locator('#Login').click();
  await page.locator('#Login').click();
  await page.locator('#Login').click();
  await page.locator('#Login').click();
  await page.locator('#Login').dblclick();
  await page.locator('#Login').dblclick();
  await page.locator('#Login').dblclick();
  await page.locator('#Login').click();
  await page.locator('#Login').click();
  await page.locator('#Login').fill('jdm.biuro@interia.eu');
  await page.getByRole('textbox', { name: 'Hasło' }).click();
  await page.getByRole('textbox', { name: 'Hasło' }).fill('Oliwia123451');
  await page.getByRole('button', { name: 'LOGOWANIE' }).click();
  await page.getByRole('button', { name: 'Go to settings' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'Nowe zamówienie' }).click();
  await page.getByRole('button', { name: 'Dodaj produkt do zamówienia' }).click();
  await page.getByRole('combobox').first().selectOption('object:392');
  await page.getByRole('combobox').first().selectOption('string:Standalone');
  await page.getByRole('combobox').nth(1).selectOption('string:Product');
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('6000');
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('5000');
  await page.getByText('Szerokość (mm) Wysięg (mm)').click();
  await page.getByRole('listbox').filter({ hasText: 'StandardStandardCiche' }).getByLabel('select').click();
  await page.getByText('StandardCiche odwodnienieBrak').click();
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.getByRole('listbox').filter({ hasText: /^$/ }).fill('7016');
  await page.getByRole('listbox').filter({ hasText: /^$/ }).click();
  await page.getByRole('listbox').filter({ hasText: /^$/ }).press('Enter');
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.locator('.k-item.ng-scope.k-state-hover > div').click();
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.locator('.k-item.ng-scope.k-state-hover > div').click();
  await page.locator('div:nth-child(8) > div').first().click();
  await page.getByRole('spinbutton').nth(2).dblclick();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).fill('6000');
  await page.getByText('Szerokość (mm) Wysięg (mm)').click();
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).fill('2400');
  await page.locator('div:nth-child(44)').click();
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-select > .k-icon').click();
  await page.locator('.k-item.ng-scope.k-state-hover > .k-state-default').click();
  await page.getByRole('combobox').nth(3).selectOption('string:N');
  await page.getByRole('combobox').nth(5).selectOption('string:W');
  await page.getByText('Next (Rolety ZIP) »').click();
  await page.getByRole('checkbox', { name: 'Dodaj rolety ZIP' }).check();
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.locator('[id="7fc05e89-6f90-454f-abab-35a435a6e692"] > .k-state-default').click();
  await page.getByText('A1-A2').click();
  await page.locator('.un_productform_right').click();
  await page.locator('a').filter({ hasText: 'Rozwiń podsumowanie' }).click();
  await page.locator('.fa.fa-edit').click();
  await page.getByRole('combobox').first().selectOption('string:5%');
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.locator('b').filter({ hasText: 'czarny/czarny 5% SC5/' }).click();
  await page.locator('a').filter({ hasText: 'Update' }).click();
  await page.getByText('Next (Napęd i automatyka) »').click();
  await page.getByRole('combobox').first().selectOption('string:Somfy');
  await page.locator('.k-dropdown-wrap.k-state-default.k-state-hover > .k-input').click();
  await page.locator('.k-item.ng-scope.k-state-hover > .k-state-default').click();
  await page.getByRole('combobox').nth(1).selectOption('string:RTSd');
  await page.locator('a').filter({ hasText: /^Konfiguracja główna$/ }).click();
  await page.getByRole('combobox').nth(4).selectOption('string:N');
  await page.getByText('Błąd: Odpływy wymagane w co').click();
  await page.locator('div:nth-child(45) > div:nth-child(4) > .dynamic-field > .form-group > .form-control').selectOption('string:S');
  await page.locator('#btn_save').click();
  await page.getByRole('button', { name: 'Zapisz' }).click();
  await page.goto('https://rolety.aliplast.pl//Order/Edit/51699#/');
  await page.getByRole('button', { name: 'Show order lines' }).click();
  await page.getByRole('button', { name: 'Zapisz' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
});