import { supabase } from '../lib/supabase';
import type { ProductConfig, PricingResult, SnowZoneInfo, TransportSettings } from '../types';
import { calculateInstallationCosts, calculateDistanceFromGubin } from '../utils/distanceCalculator';
import catalogData from '../data/catalog.json';

// --- Types for New Manual Pricing ---

export interface BasePriceEntry {
    id: string;
    model_family: string;
    construction_type: string;
    cover_type: string;
    zone: number;
    width_mm: number;
    depth_mm: number;
    price_upe_net_eur: number;
    currency: string;
}

export interface AddonPriceEntry {
    id: string;
    addon_code: string;
    addon_name: string;
    pricing_basis: 'FIXED' | 'PER_M2' | 'BY_WIDTH' | 'BY_OPENING_WIDTH' | 'MANUAL' | 'PERCENTAGE';
    price_upe_net_eur: number;
    unit: string;
    addon_group?: string;
    properties?: Record<string, any>;
}

export interface AdditionalCost {
    id?: string;
    name?: string;
    cost_type: 'fixed' | 'percentage';
    value: number;
    description?: string;
    attributes?: Record<string, any>;
}

export const PricingService = {

    /**
     * Get distinct model families from pricing_base to populate Product Dropdown.
     */
    async getMainProducts(): Promise<{ id: string, code: string, name: string, description: string, category: string, image_url?: string, standard_colors?: string[], custom_color_surcharge_percentage?: number, configuration?: any }[]> {
        // Fetch Parallel: Definitions, Base Pricing, Table Pricing
        const [
            { data: dbProducts },
            { data: manualData },
            { data: tableData }
        ] = await Promise.all([
            supabase.from('product_definitions').select('*').order('name'),
            supabase.from('pricing_base').select('model_family').limit(50000),
            supabase.from('price_tables').select('name')
        ]);

        // 1. Identify "Active Models" from PRICING data
        const activeModelNames = new Set<string>();

        // From Base Pricing (Legacy)
        (manualData || []).forEach(d => {
            if (d.model_family) activeModelNames.add(d.model_family.trim().toLowerCase());
        });

        // From Price Tables (New)
        (tableData || []).forEach(t => {
            if (t.name) {
                // Remove "Manual Import - " prefix if present (generated by Importer)
                let cleanName = t.name;
                if (cleanName.startsWith('Manual Import - ')) {
                    cleanName = cleanName.replace('Manual Import - ', '');
                }

                // Heuristic: "ModelName - Variant" -> "ModelName"
                const modelName = cleanName.split(' - ')[0].trim().toLowerCase();

                if (modelName) activeModelNames.add(modelName);
            }
        });

        // 2. Filter Database Definitions and Deduplicate
        // If a product is defined in DB but has NO pricing (neither base nor table), hide it.
        // Also ensure we don't show duplicates if DB has multiple entries for same name.
        const seenDbModels = new Set<string>();
        const filteredDbProducts: any[] = [];

        for (const p of (dbProducts || [])) {
            const nameKey = (p.name || '').trim().toLowerCase();
            const codeKey = (p.code || '').trim().toLowerCase();

            // Check if active (exists in pricing)
            if (activeModelNames.has(nameKey) || activeModelNames.has(codeKey)) {
                // Check if already added to list (Deduplication)
                const uniqueKey = nameKey || codeKey;

                if (seenDbModels.has(uniqueKey)) {
                    // Conflict! We already have a product for this key.
                    // Let's see if the NEW one (p) is better than the OLD one (stored in map/list).
                    // We need to find the index of the existing one.
                    const existingIdx = filteredDbProducts.findIndex(ep =>
                        (ep.name || '').trim().toLowerCase() === uniqueKey ||
                        (ep.code || '').trim().toLowerCase() === uniqueKey
                    );

                    if (existingIdx !== -1) {
                        const existing = filteredDbProducts[existingIdx];
                        // Preference Logic:
                        // 1. Prefer ones with actual configuration/colors over empties
                        // 2. Prefer 'Manual' provider (if flagged)
                        // 3. Prefer most recently updated (if we had timestamp, assuming p is newer or checking field)

                        const existingHasConfig = existing.standard_colors?.length > 0 || existing.configuration;
                        const newHasConfig = p.standard_colors?.length > 0 || p.configuration;

                        if (newHasConfig && !existingHasConfig) {
                            // Replace old with new
                            filteredDbProducts[existingIdx] = p;
                        }
                    }
                } else {
                    filteredDbProducts.push(p);
                    seenDbModels.add(uniqueKey);
                }
            }
        }

        const combined = [...filteredDbProducts];

        // 3. Add Psuedo-Products (If active in pricing but missing from DB)
        activeModelNames.forEach(activeName => {
            // Check if we already have it in combined (case-insensitive check)
            const exists = combined.some(p =>
                (p.name || '').trim().toLowerCase() === activeName ||
                (p.code || '').trim().toLowerCase() === activeName
            );

            if (!exists) {
                // Restore original casing heuristic (Capitalize first letter)
                const displayName = activeName.charAt(0).toUpperCase() + activeName.slice(1);

                combined.push({
                    id: '', // No ID
                    code: activeName, // internal code matches pricing key
                    name: displayName,
                    description: 'Manual Pricing Model',
                    category: 'roof',
                    image_url: undefined,
                    standard_colors: undefined,
                    custom_color_surcharge_percentage: undefined,
                    configuration: {}
                });
            }
        });

        return combined.map(p => ({
            id: p.id,
            code: p.code,
            name: p.name,
            description: p.description || 'Manual Pricing Model',
            category: p.category,
            image_url: p.image_url,
            standard_colors: p.standard_colors,
            custom_color_surcharge_percentage: p.custom_color_surcharge_percentage,
            configuration: p.configuration
        }));
    },

    /**
     * Create or Update Product Definition
     */
    async upsertProductDefinition(product: Partial<{ id: string, name: string, code: string, description: string, image_url: string, standard_colors: string[], custom_color_surcharge_percentage: number, configuration: any }>) {
        if (!product.name) throw new Error("Name is required");

        // Auto-generate code if missing
        const code = product.code || product.name.toLowerCase().replace(/\s+/g, '_');

        const payload: Record<string, unknown> = {
            name: product.name,
            code: code,
            category: 'roof', // Default
            provider: 'Manual',
            updated_at: new Date()
        };

        if (product.description !== undefined) payload.description = product.description;
        if (product.image_url !== undefined) payload.image_url = product.image_url;
        if (product.standard_colors !== undefined) payload.standard_colors = product.standard_colors;
        if (product.custom_color_surcharge_percentage !== undefined) payload.custom_color_surcharge_percentage = product.custom_color_surcharge_percentage;
        if (product.configuration !== undefined) payload.configuration = product.configuration;

        if (product.id) {
            return supabase.from('product_definitions').update(payload).eq('id', product.id).select().single();
        } else {
            return supabase.from('product_definitions').insert(payload).select().single();
        }
    },

    /**
     * Get Product Image URL based on configuration
     */
    async getProductImage(modelId: string, _context: { roofType?: string, snowZone?: string }): Promise<string | undefined> {
        // Simple lookup from catalog for now
        // In future could query DB if images are variant-specific
        const models = catalogData.models as Array<{ id: string, image: string }>;
        const model = models.find(m => m.id.toLowerCase() === modelId.toLowerCase());
        return model?.image;
    },

    /**
     * Get Product Dimension Limits
     */
    async getProductLimits(modelId: string): Promise<{ minWidth: number, maxWidth: number, minDepth: number, maxDepth: number }> {
        const defaultLimits = { minWidth: 2000, maxWidth: 14000, minDepth: 2000, maxDepth: 6000 };

        try {
            // Run parallel queries for efficiency
            const [minW, maxW, minD, maxD] = await Promise.all([
                supabase.from('pricing_base').select('width_mm').eq('model_family', modelId).order('width_mm', { ascending: true }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('width_mm').eq('model_family', modelId).order('width_mm', { ascending: false }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('depth_mm').eq('model_family', modelId).order('depth_mm', { ascending: true }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('depth_mm').eq('model_family', modelId).order('depth_mm', { ascending: false }).limit(1).maybeSingle()
            ]);

            return {
                minWidth: minW.data?.width_mm || defaultLimits.minWidth,
                maxWidth: maxW.data?.width_mm || defaultLimits.maxWidth,
                minDepth: minD.data?.depth_mm || defaultLimits.minDepth,
                maxDepth: maxD.data?.depth_mm || defaultLimits.maxDepth
            };
        } catch (e) {
            console.error('Error fetching product limits:', e);
            return defaultLimits;
        }
    },

    /**
     * Exact Match Lookup for Base Price with Smart Fallback
     */
    async findBasePrice(criteria: {
        modelFamily: string;
        constructionType: 'wall' | 'free';
        coverType: string;
        zone: number;
        width: number;
        depth: number;
    }): Promise<{ price: number, variant_note?: string } | null> {
        console.log('🔍 Pricing Lookup:', criteria);

        // 1. Try Exact Match
        const { data: exactData } = await supabase
            .from('pricing_base')
            .select('price_upe_net_eur, variant_note')
            .ilike('model_family', criteria.modelFamily)
            .eq('construction_type', criteria.constructionType)
            .ilike('cover_type', criteria.coverType)
            .eq('zone', criteria.zone)
            .eq('width_mm', criteria.width)
            .eq('depth_mm', criteria.depth)
            .maybeSingle();

        if (exactData) {
            console.log('✅ Exact Price Found:', exactData.price_upe_net_eur);
            return { price: exactData.price_upe_net_eur, variant_note: exactData.variant_note };
        }

        // 2. Smart Match (Next Larger)
        const { data: smartData } = await supabase
            .from('pricing_base')
            .select('price_upe_net_eur, width_mm, depth_mm, variant_note')
            .ilike('model_family', criteria.modelFamily) // Case-insensitive Family match
            .eq('construction_type', criteria.constructionType)
            .ilike('cover_type', criteria.coverType)
            .eq('zone', criteria.zone) // Strict Zone match (safety)
            .gte('width_mm', criteria.width)
            .gte('depth_mm', criteria.depth)
            .order('width_mm', { ascending: true })
            .order('depth_mm', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (smartData) {
            console.log(`✅ Smart Match Found: Requested ${criteria.width}x${criteria.depth} -> Used ${smartData.width_mm}x${smartData.depth_mm}`);
            return { price: smartData.price_upe_net_eur, variant_note: smartData.variant_note };
        }

        console.warn('❌ Base Price Not Found. Attempting Manual Table Lookup...');

        // 3. Manual Table Lookup (Fallback for Raw Imports)
        // Check construction type: Surcharges rely on Base (Wall) + Surcharge.
        // If request is for 'free', we should return NULL here so the Service falls back to "Wall + Surcharge".
        // UNLESS the table explicitly says "Freestanding".
        const requestIsWall = criteria.constructionType === 'wall';

        const { data: manualTables } = await supabase
            .from('price_tables')
            .select('*')
            .ilike('name', `%${criteria.modelFamily}%`) as { data: any[] | null }; // Broad match on model name

        if (manualTables && manualTables.length > 0) {
            // Filter in JS for best match using Scoring System
            // We need to match criteria.zone and criteria.coverType

            // 1. Identify Target Keys
            const typeKey = criteria.coverType.includes('glass') ? 'Glass' : 'Poly';
            const zoneKey = `S${criteria.zone}`; // e.g. "S1"

            // Subtype Nuances
            const isRelax = criteria.coverType.includes('relax') || criteria.coverType.includes('gold') || criteria.coverType.includes('ir');
            const isOpal = criteria.coverType.includes('opal');
            const isClear = criteria.coverType.includes('clear') || (!isRelax && !isOpal);

            // 2. Score Tables
            let bestMatch: any = null;
            let bestScore = -100;

            console.log(`🔎 Searching Manual Tables for: ${criteria.modelFamily} (${criteria.coverType}) Zone:${criteria.zone} Type:${criteria.constructionType}`);

            manualTables.forEach(t => {
                const name = t.name.toLowerCase();
                let score = 0;

                // A. Construction Type Check (Critical)
                const isExplicitFree = name.includes('freestanding') || name.includes('wolnostoj');
                if (requestIsWall && isExplicitFree) return; // Disqualify
                if (!requestIsWall && !isExplicitFree) return; // Disqualify
                score += 10; // Construction type matches

                // B. Zone Check (Critical)
                // "Trendstyle - S1" matches "s1"
                // Also support "Zone 1" or "Z1"
                const hasZone = name.includes(` ${zoneKey.toLowerCase()}`) || name.includes(`-${zoneKey.toLowerCase()}`) || name.includes(`s${criteria.zone}`);
                if (!hasZone) return; // Disqualify (Zone mismatch is fatal usually)
                score += 10;

                // C. Material Check (High Priority)
                if (typeKey === 'Glass' && !name.includes('glass') && !name.includes('szkło')) {
                    // If searching for Glass but table doesn't say Glass, it might be Poly by default? 
                    // Or "Trendstyle - S1" is generic? Assuming generic is Poly usually.
                    // Score penalty if mismatch type
                }

                // D. Subtype Specifics (The IR Gold Fix)
                if (isRelax) {
                    if (name.includes('relax') || name.includes('ir') || name.includes('gold')) {
                        score += 50; // Huge boost for specific match
                    } else {
                        score -= 20; // Penalty for picking non-relax table when we want relax
                    }
                } else if (isOpal) {
                    if (name.includes('opal') || name.includes('mlecz')) {
                        score += 50;
                    } else {
                        score -= 10;
                    }
                } else if (isClear) {
                    // If we want clear, we prefer NOT to see "Relax" or "Opal"
                    if (name.includes('relax') || name.includes('gold') || name.includes('opal')) {
                        score -= 50; // Strong penalty: Don't pick a specialized table for clear
                    } else {
                        score += 10; // Neutral/Correct
                    }
                }

                // E. Tie Breaker for "Genric" vs "Specific" names?
                // Shorter names might be more generic.

                // console.log(`   ? Checking: ${t.name} -> Score: ${score}`);

                if (score > bestScore) {
                    bestScore = score;
                    bestMatch = t;
                }
            });

            const match = bestMatch;

            if (match && match.rows) {
                console.log(`✅ Selected Manual Table: ${match.name} (Score: ${bestScore})`);
                // Parse JSON Grid
                // rows: { width: number, ...projections: { [depth]: price } }
                const rows = match.rows as any[];

                // Sort by width
                const sortedRows = rows.sort((a, b) => a.width - b.width);

                // Find Row >= Width
                const row = sortedRows.find(r => r.width >= criteria.width);

                // ... (rest is same)
                if (row) {
                    // Check Projections in this row
                    // row = { width: 3000, "2000": 1500, "2500": 1600 ... }
                    // Find key >= depth
                    const depths = Object.keys(row).filter(k => k !== 'width' && !isNaN(Number(k))).map(Number).sort((a, b) => a - b);
                    const matchedDepth = depths.find(d => d >= criteria.depth);

                    if (matchedDepth) {
                        const price = Number(row[matchedDepth]);
                        if (price && !isNaN(price)) {
                            console.log(`✅ Manual Table Match: ${match.name} (W:${row.width} x D:${matchedDepth}) = ${price}`);
                            return { price, variant_note: 'Manual Table Price' };
                        }
                    }
                }
            }
        }

        return null; // Return null to indicate failure
    },

    /**
     * Main Calculation Function replacing legacy calculateOfferPrice
     */
    async calculateOfferPrice(
        product: ProductConfig,
        marginPercentage: number, // e.g. 0.30 for 30% MARGIN (Selling = Cost / (1-0.3))
        snowZone?: SnowZoneInfo,
        postalCode?: string
    ): Promise<PricingResult> {

        // 1. Normalize Inputs
        // 1. Normalize Inputs
        // const modelFamily = product.modelId.charAt(0).toUpperCase() + product.modelId.slice(1); // Unused
        const constructionType = product.installationType === 'freestanding' ? 'free' : 'wall';

        let coverType = 'poly_clear'; // Default
        if (product.roofType === 'glass') {
            // Map legacy glass types or defaults
            if (product.glassType === 'mat' || product.glassType === 'glass_opal') coverType = 'glass_opal';
            else if (product.glassType === 'sunscreen' || product.glassType === 'glass_tinted') coverType = 'glass_tinted';
            else coverType = 'glass_clear';
        } else {
            // Poly mappings
            if (product.polycarbonateType === 'poly_opal') coverType = 'poly_opal';
            else if (product.polycarbonateType === 'iq-relax' || product.polycarbonateType === 'ir-gold' || product.polycarbonateType === 'poly_iq_relax') coverType = 'poly_iq_relax';
            else coverType = 'poly_clear';
        }

        // Snow Zone
        let zone = 1;
        if (snowZone && snowZone.id) {
            // Usually '1', '2', '3'... parse int
            const parsed = parseInt(String(snowZone.id));
            if (!isNaN(parsed)) zone = parsed;
        }

        // 2. Lookup Base Price
        // Check for "Additive Freestanding" configuration
        // Check for "Additive Freestanding" configuration
        // FIX: Fetch all matches and find the one with actual configuration.
        // DEDUPLICATION LOGIC for Calculator:
        let allDefData: any[] = [];
        try {
            // Try fetching configuration (might fail if column missing)
            const { data, error } = await supabase
                .from('product_definitions')
                .select('id, configuration, code')
                .ilike('code', product.modelId);

            if (!error && data) allDefData = data;
        } catch (e) {
            console.warn('Configuration column likely missing, fetching without it');
            const { data } = await supabase
                .from('product_definitions')
                .select('id, code')
                .ilike('code', product.modelId);
            if (data) allDefData = data;
        }

        // Find the "Best" record (Prioritize ones with configuration)
        let defData = (allDefData || []).sort((a: any, b: any) => {
            const hasConfigA = a.configuration && (a.configuration.freestanding_is_additive || (a.configuration.freestanding_surcharge_rules?.length > 0));
            const hasConfigB = b.configuration && (b.configuration.freestanding_is_additive || (b.configuration.freestanding_surcharge_rules?.length > 0));
            return (hasConfigB ? 1 : 0) - (hasConfigA ? 1 : 0);
        })[0];

        // FALLBACK: If no config on Product, check duplicate products OR Price Tables
        let productConfig = defData?.configuration || {};

        // If config is empty, check Price Tables (Legacy/Admin Store)
        if (!productConfig.freestanding_surcharge_rules) {
            console.log('🔄 Checking Price Tables for missing configuration (Smart Fallback)...');

            // SUPER FALLBACK: Search by CODE, not just ID.
            // This fixes the "Lottery" where Admin saves to Product A, but Calculator finds Product B.
            // We find ANY table linked to ANY product with this Code.
            const { data: tableData } = await supabase
                .from('price_tables')
                .select('configuration, product:product_definitions!inner(code)')
                .eq('product.code', product.modelId) // Inner Join on Code
                .order('created_at', { ascending: false })
                .limit(1)
                .maybeSingle();

            if (tableData?.configuration) {
                console.log('✅ Found Configuration in Price Table via Code Match (Super Fallback)');
                productConfig = { ...productConfig, ...tableData.configuration };
            } else if (defData?.id) {
                // Try ID fallback loop (simple) just in case join fails
                const { data: simpleTable } = await supabase
                    .from('price_tables')
                    .select('configuration')
                    .eq('product_definition_id', defData.id)
                    .order('created_at', { ascending: false })
                    .limit(1)
                    .maybeSingle();
                if (simpleTable?.configuration) {
                    productConfig = { ...productConfig, ...simpleTable.configuration };
                }
            }
        }

        const isAdditive = productConfig.freestanding_is_additive === true;
        const useAdditiveLogic = isAdditive && constructionType === 'free';

        let priceResult = null;

        if (useAdditiveLogic) {
            console.log('⚡ Force Additive Logic for Freestanding (Configured)');
            priceResult = await this.findBasePrice({
                modelFamily: product.modelId,
                constructionType: 'wall', // Force Wall Lookup
                coverType,
                zone,
                width: product.width,
                depth: product.projection
            });
        } else {
            // Standard Lookup
            priceResult = await this.findBasePrice({
                modelFamily: product.modelId,
                constructionType,
                coverType,
                zone,
                width: product.width,
                depth: product.projection
            });
        }

        // [FallBack OR Additive] If Freestanding price not found in base table (or forced additive), try Wall Base + Freestanding Surcharge
        let freestandingSurcharge = 0;

        // Logical OR: It is additive config OR standard fallback scenario
        if (useAdditiveLogic || (!priceResult && constructionType === 'free')) {
            if (!useAdditiveLogic) console.log('⚠️ Freestanding base price not found. Attempting Wall Base + Surcharge fallback.');

            // If we don't have a price yet (Fallback case), try fetching Wall price
            if (!priceResult) {
                // If this is strict Additive mode, we ALREADY checked Wall price above.
                // If it's Legacy fallback mode, we check it now.
                priceResult = await this.findBasePrice({
                    modelFamily: product.modelId,
                    constructionType: 'wall', // Force Wall
                    coverType,
                    zone,
                    width: product.width,
                    depth: product.projection
                });
            }

            if (priceResult) {
                // Determine Surcharge Source
                const rules = defData?.configuration?.freestanding_surcharge_rules;

                if (rules && Array.isArray(rules) && rules.length > 0) {
                    // 1. Use Inline Configuration Rules (STRICT PRIORITY)
                    console.log('⚡ Using Configured Surcharge Rules');
                    const sorted = [...rules].sort((a: any, b: any) => a.max_width - b.max_width);

                    // User Request: "reguły z cennika dają kwotę dopłaty... Reszte usuń"
                    // Find the first rule where rule.max_width >= product.width
                    const match = sorted.find((r: any) => Number(r.max_width) >= product.width);

                    if (match) {
                        freestandingSurcharge = Number(match.price);
                        console.log(`⚡ Surcharge Applied: ${freestandingSurcharge} EUR (Limit: ${match.max_width}mm)`);
                    } else {
                        // Exceeds max defined width
                        const maxRule = sorted[sorted.length - 1];
                        freestandingSurcharge = Number(maxRule.price);
                        console.warn(`⚠️ Width ${product.width} exceeds max rule (${maxRule.max_width}). Using max price: ${freestandingSurcharge}`);
                    }
                } else {
                    // ZERO TOLERANCE: If no rules configured, Surcharge is 0.
                    // User explicitly requested to remove "ghost" prices from legacy DB.
                    console.log('ℹ️ No freestanding rules found. Surcharge = 0.');
                    freestandingSurcharge = 0;
                }
            }
        }

        let safeBasePrice = (priceResult?.price || 0) + freestandingSurcharge;

        // Ensure dbPriceFound reflects success even if we used fallback
        const dbPriceFound = priceResult !== null;
        const structuralNote = priceResult?.variant_note;

        // 3. Addons Total
        let addonsTotal = 0;
        (product.selectedAccessories || []).forEach(acc => {
            addonsTotal += (acc.price || 0) * (acc.quantity || 1);
        });

        // 4. Custom Items
        let customItemsTotal = 0;
        (product.customItems || []).forEach(item => {
            customItemsTotal += (item.price || 0) * (item.quantity || 1);
        });

        // 5. Installation
        // 5. Installation
        // Fetch settings dynamically to ensure accuracy (avoid stale defaults)
        let transportSettings: TransportSettings | undefined;
        try {
            const { data } = await supabase.from('app_settings').select('value').eq('key', 'transport_settings').maybeSingle();
            if (data?.value) {
                transportSettings = data.value as TransportSettings;
            }
        } catch (e) {
            console.warn('Failed to fetch transport settings in pricing service', e);
        }

        const distance = calculateDistanceFromGubin(postalCode || '', transportSettings?.baseLocation);
        const installation = calculateInstallationCosts(product.installationDays || 1, distance || 0, transportSettings?.ratePerKm);

        // 6. Final Calculation
        // Manual Override logic
        const effectiveBase = (product.isManual && product.manualPrice) ? product.manualPrice : safeBasePrice;

        const totalCost = effectiveBase + addonsTotal + customItemsTotal + (installation.dailyTotal || 0) + (installation.travelCost || 0);

        // Margin Calculation (Margin vs Markup?)
        // Assuming MARGIN: Price = Cost / (1 - Margin%)
        // marginPercentage is usually 0-100 in input? Or 0.3?
        // Let's assume input comes as integer percentage (30) or checks.
        // Usually Types say `marginPercentage: number`.

        // Safety check
        const marginDecimal = marginPercentage > 1 ? marginPercentage / 100 : marginPercentage;
        const safeMargin = Math.min(Math.max(marginDecimal, 0), 0.99); // Cap at 99%

        const sellingPriceNet = totalCost / (1 - safeMargin);
        const marginValue = sellingPriceNet - totalCost;

        // VAT
        const sellingPriceGross = sellingPriceNet * 1.19; // DE 19% default

        return {
            basePrice: effectiveBase,
            addonsPrice: addonsTotal,
            customItemsPrice: customItemsTotal,
            totalCost,
            marginPercentage: safeMargin * 100,
            marginValue,
            sellingPriceNet: parseFloat(sellingPriceNet.toFixed(2)),
            sellingPriceGross: parseFloat(sellingPriceGross.toFixed(2)),
            installationCosts: installation,

            _debuginfo: {
                found: dbPriceFound,
                info: `Model: ${product.modelId}, W:${product.width} D:${product.projection} Z:${zone}`
            },
            structuralNote // Propagate the note to the offer
        };
    },

    /**
     * Fetch Matrix (All Rows) for Client-Side Filtering
     * Used by ProductConfigurator to find "Next Size Up" locally or get exact match details.
     */
    async getPriceMatrix(modelId: string, attributes: Record<string, string>) {
        console.log('Fetching Price Matrix for:', modelId, attributes);
        const zone = parseInt(attributes.snow_zone || '1');
        const constructionType = attributes.mounting === 'wall-mounted' ? 'wall' : (attributes.mounting || 'wall');
        const coverTypeQuery = attributes.subtype || '';

        // Build query
        let query = supabase
            .from('pricing_base')
            .select('*')
            .ilike('model_family', modelId)
            .eq('zone', zone);

        // Handle construction type if present in DB (some models might not have it?)
        // Assuming pricing_base has construction_type
        // Check for Additive Configuration
        const { data: defData } = await supabase
            .from('product_definitions')
            .select('configuration')
            .ilike('code', modelId)
            .maybeSingle();

        const isAdditive = defData?.configuration?.freestanding_is_additive === true;

        if (constructionType) {
            // IF Additive AND Freestanding requested -> Use Wall Base Price
            if (isAdditive && (constructionType === 'free' || constructionType === 'freestanding')) {
                console.log(`⚡ getPriceMatrix: Forcing Wall Lookup for Additive Freestanding Model (${modelId})`);
                query = query.eq('construction_type', 'wall');
            } else {
                query = query.eq('construction_type', constructionType);
            }
        }

        // Handle Cover Type with wildcards for generic types
        if (coverTypeQuery) {
            // If query is 'glass', match 'glass_clear', 'glass_opal', etc.
            // If query is 'polycarbonate', match 'poly_clear', 'poly_opal'
            if (coverTypeQuery.toLowerCase() === 'glass') {
                query = query.ilike('cover_type', '%glass%');
            } else if (coverTypeQuery.toLowerCase() === 'polycarbonate') {
                query = query.ilike('cover_type', '%poly%');
            } else {
                query = query.ilike('cover_type', `%${coverTypeQuery}%`);
            }
        }

        const { data, error } = await query;

        if (error) {
            console.error('Error fetching matrix:', error);
            return [];
        }
        return data || [];
    },

    /**
     * Find best match in the matrix for given dimensions.
     * Returns { total, variant_note, properties: { matchedWidth, matchedProjection } }
     */
    getDetailedPrice(matrix: any[], width: number, depth: number) {
        if (!matrix || matrix.length === 0) return { total: 0 };

        // 1. Try Exact or Best Match (Next Larger)
        // Sort by area (width*depth) ascending
        const sorted = [...matrix].sort((a, b) => (a.width_mm * a.depth_mm) - (b.width_mm * b.depth_mm));

        // Find match: width >= requested AND depth >= requested
        const match = sorted.find(row => row.width_mm >= width && row.depth_mm >= depth);

        if (match) {
            return {
                total: match.price_upe_net_eur,
                variant_note: match.variant_note,
                properties: {
                    matchedWidth: match.width_mm,
                    matchedProjection: match.depth_mm,
                    posts: match.posts,
                    fields: match.fields,
                    posts_count: match.posts_count,
                    fields_count: match.fields_count
                }
            };
        }

        return { total: 0 };
    },

    async getAvailableSurcharges(modelId: string, attributes: Record<string, string>) {
        if (!modelId) return [];

        try {
            // Get unique surcharge types available for this model family
            const { data, error } = await supabase
                .from('pricing_surcharges')
                .select('surcharge_type, price_eur')
                .ilike('model_family', modelId)
            // .eq('width_mm', 0) // Typically global surcharges might have width 0 or specific width?
            // Actually, surcharges vary by width. Use distinct on type to get NAMES.
            // But we need a price for display? Price might depend on width!
            // For UI "Option List", we just need the IDs/Names.
            // Let's get distinct types.
            // .order('surcharge_type');

            if (error) {
                console.error('Error fetching available surcharges:', error);
                return [];
            }

            // To get distinct types with a representative price (e.g. min price or just for listing)
            // Supabase distinct is tricky. Let's fetch all and dedupe in JS for now or use .rpc if needed.
            // Better: select distinct surcharge_type? simple .select() doesn't do distinct well without query modification.
            // Let's just return a static list of KNOWN surcharges if DB is complex, OR fetch all and unique.

            // Temporary robust approach: Fetch all for model, unique by type
            const unique = new Map();
            data?.forEach(item => {
                if (!unique.has(item.surcharge_type)) {
                    unique.set(item.surcharge_type, {
                        id: item.surcharge_type,
                        name: item.surcharge_type.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase()), // Prettify
                        price: item.price_eur // Just a sample price
                    });
                }
            });

            return Array.from(unique.values());

        } catch (e) {
            console.error('getAvailableSurcharges exception:', e);
            return [];
        }
    },

    async getAdditionalCosts(modelId: string, attributes: Record<string, string>) {
        return [];
    },

    async getTableConfig(modelId: string, attributes: Record<string, string>) {
        return { config: {} as any, attributes: {} as any };
    },

    calculateSurcharges(basePrice: number, width: number, depth: number, config: any, context: any): { total: number, items: { name: string, price: number }[] } {
        return { total: 0, items: [] };
    },

    async getSurchargePrice(modelFamily: string, surchargeType: string, width: number): Promise<number> {
        console.log(`💰 Surcharge Lookup: ${modelFamily} - ${surchargeType} (Width: ${width})`);

        // 1. Priority: Check Configuration Rules (e.g. Freestanding Rules from Admin)
        if (surchargeType === 'freestanding') {
            const { data: defData } = await supabase
                .from('product_definitions')
                .select('configuration')
                .ilike('code', modelFamily)
                .maybeSingle();

            const rules = defData?.configuration?.freestanding_surcharge_rules;
            if (rules && Array.isArray(rules) && rules.length > 0) {
                console.log('⚡ Found Freestanding Rules in Configuration');
                const sorted = [...rules].sort((a: any, b: any) => a.max_width - b.max_width);
                const match = sorted.find((r: any) => Number(r.max_width) >= width);

                if (match) {
                    console.log(`✅ Rule Matched: ${match.price} EUR (Limit: ${match.max_width}mm)`);
                    return Number(match.price);
                } else {
                    // Exceeds max rule - use largest
                    const maxRule = sorted[sorted.length - 1];
                    console.warn(`⚠️ Width ${width} exceeds max rule. Using max: ${maxRule.price}`);
                    return Number(maxRule.price);
                }
            }
        }

        // 2. Fallback: Legacy Table (pricing_surcharges)
        const { data } = await supabase
            .from('pricing_surcharges')
            .select('price_eur, width_mm')
            .eq('model_family', modelFamily)
            .eq('surcharge_type', surchargeType)
            .gte('width_mm', width)
            .order('width_mm', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (data) {
            console.log(`✅ Surcharge Found (Legacy Table): ${data.price_eur} EUR (Matched Width: ${data.width_mm})`);
            return data.price_eur;
        }

        return 0;
    },

    calculateDiscountedPrice(price: number, discount: string) {
        return price;
    },

    // --- Legacy / Compatibility Stubs ---
    async checkPriceTableExists() { return true; },
    async getMatrixTables() { return []; },
    async getComponentLists() { return []; },

    async getAddonsByGroup(group: string) {
        try {
            const { data: addons } = await supabase.from('pricing_addons').select('*').eq('addon_group', group);

            if (!addons || addons.length === 0) return [];

            // Fetch metadata from product_components
            const keys = addons.map(a => a.addon_code).filter(k => k);
            const { data: meta } = await supabase
                .from('product_components')
                .select('component_key, image_url, description')
                .in('component_key', keys);

            // Map metadata
            const merged = addons.map(addon => {
                const info = meta?.find(m => m.component_key === addon.addon_code);
                return {
                    ...addon,
                    image_url: info?.image_url,
                    description: info?.description || addon.addon_name
                };
            });

            return merged;
        } catch (e) {
            console.error('Error fetching addons group:', group, e);
            return [];
        }
    }
};
