import { supabase } from '../lib/supabase';
import type { ProductConfig, PricingResult, SnowZoneInfo, TransportSettings } from '../types';
import { calculateInstallationCosts, calculateDistanceFromGubin, type InstallationDailyRates } from '../utils/distanceCalculator';
import { DatabaseService } from './database';
import catalogData from '../data/catalog.json';

// --- Types for New Manual Pricing ---

export interface BasePriceEntry {
    id: string;
    model_family: string;
    construction_type: string;
    cover_type: string;
    zone: number;
    width_mm: number;
    depth_mm: number;
    price_upe_net_eur: number;
    currency: string;
}

export interface AddonPriceEntry {
    id: string;
    addon_code: string;
    addon_name: string;
    pricing_basis: 'FIXED' | 'PER_M2' | 'BY_WIDTH' | 'BY_OPENING_WIDTH' | 'MANUAL' | 'PERCENTAGE';
    price_upe_net_eur: number;
    unit: string;
    addon_group?: string;
    properties?: Record<string, unknown>;
}

export interface AdditionalCost {
    id?: string;
    name?: string;
    cost_type: 'fixed' | 'percentage';
    value: number;
    description?: string;
    attributes?: Record<string, unknown>;
}

export const PricingService = {

    /**
     * Get distinct model families from pricing_base to populate Product Dropdown.
     */
    async getMainProducts(): Promise<{ id: string, code: string, name: string, description: string, category: string, image_url?: string, standard_colors?: string[], custom_color_surcharge_percentage?: number, configuration?: Record<string, unknown> }[]> {
        // Fetch Parallel: Definitions, Base Pricing, Table Pricing
        const [
            { data: dbProducts },
            { data: manualData },
            { data: tableData }
        ] = await Promise.all([
            supabase.from('product_definitions').select('*').order('name'),
            supabase.from('pricing_base').select('model_family').limit(50000),
            supabase.from('price_tables').select('name')
        ]);

        // Store settings globally or in a cache if possible, but for now we might need to fetch them in calculateOfferPrice
        // Actually, mainsProducts doesn't calculate price. calculateOfferPrice does.
        // So we leave this alone and go to calculateOfferPrice.

        // Wait, calculateOfferPrice is static/arrow function in object.
        // We will fetch settings inside calculateOfferPrice.

        // 1. Identify "Active Models" from PRICING data
        const activeModelNames = new Set<string>();

        // From Base Pricing (Legacy)
        (manualData || []).forEach(d => {
            if (d.model_family) activeModelNames.add(d.model_family.trim().toLowerCase());
        });

        // From Price Tables (New)
        (tableData || []).forEach(t => {
            if (t.name) {
                // Remove "Manual Import - " prefix if present (generated by Importer)
                let cleanName = t.name;
                if (cleanName.startsWith('Manual Import - ')) {
                    cleanName = cleanName.replace('Manual Import - ', '');
                }

                // Heuristic: "ModelName - Variant" -> "ModelName"
                const modelName = cleanName.split(' - ')[0].trim().toLowerCase();

                if (modelName) activeModelNames.add(modelName);
            }
        });

        // 2. Filter Database Definitions and Deduplicate
        // If a product is defined in DB but has NO pricing (neither base nor table), hide it.
        // Also ensure we don't show duplicates if DB has multiple entries for same name.
        const seenDbModels = new Set<string>();
        const filteredDbProducts: any[] = [];

        for (const p of (dbProducts || [])) {
            const nameKey = (p.name || '').trim().toLowerCase();
            const codeKey = (p.code || '').trim().toLowerCase();

            // Check if active (exists in pricing)
            if (activeModelNames.has(nameKey) || activeModelNames.has(codeKey)) {
                // Check if already added to list (Deduplication)
                const uniqueKey = nameKey || codeKey;

                if (seenDbModels.has(uniqueKey)) {
                    // Conflict! We already have a product for this key.
                    // Let's see if the NEW one (p) is better than the OLD one (stored in map/list).
                    // We need to find the index of the existing one.
                    const existingIdx = filteredDbProducts.findIndex((ep: { name: string; code: string; }) =>
                        (ep.name || '').trim().toLowerCase() === uniqueKey ||
                        (ep.code || '').trim().toLowerCase() === uniqueKey
                    );

                    if (existingIdx !== -1) {
                        const existing = filteredDbProducts[existingIdx];
                        // Preference Logic:
                        // 1. Prefer ones with actual configuration/colors over empties
                        // 2. Prefer 'Manual' provider (if flagged)
                        // 3. Prefer most recently updated (if we had timestamp, assuming p is newer or checking field)

                        const existingHasConfig = existing.standard_colors?.length > 0 || existing.configuration;
                        const newHasConfig = p.standard_colors?.length > 0 || p.configuration;

                        if (newHasConfig && !existingHasConfig) {
                            // Replace old with new
                            filteredDbProducts[existingIdx] = p;
                        }
                    }
                } else {
                    filteredDbProducts.push(p);
                    seenDbModels.add(uniqueKey);
                }
            }
        }

        const combined = [...filteredDbProducts];

        // 3. Add Psuedo-Products (If active in pricing but missing from DB)
        activeModelNames.forEach(activeName => {
            // Check if we already have it in combined (case-insensitive check)
            const exists = combined.some(p =>
                (p.name || '').trim().toLowerCase() === activeName ||
                (p.code || '').trim().toLowerCase() === activeName
            );

            if (!exists) {
                // Restore original casing heuristic (Capitalize first letter)
                const displayName = activeName.charAt(0).toUpperCase() + activeName.slice(1);

                combined.push({
                    id: '', // No ID
                    code: activeName, // internal code matches pricing key
                    name: displayName,
                    description: 'Manual Pricing Model',
                    category: 'roof',
                    image_url: undefined,
                    standard_colors: undefined,
                    custom_color_surcharge_percentage: undefined,
                    configuration: {}
                });
            }
        });

        return combined.map(p => ({
            id: p.id,
            code: p.code,
            name: p.name,
            description: p.description || 'Manual Pricing Model',
            category: p.category,
            image_url: p.image_url,
            standard_colors: p.standard_colors,
            custom_color_surcharge_percentage: p.custom_color_surcharge_percentage,
            configuration: p.configuration
        }));
    },

    /**
     * Create or Update Product Definition
     */
    async upsertProductDefinition(product: Partial<{ id: string, name: string, code: string, description: string, image_url: string, standard_colors: string[], custom_color_surcharge_percentage: number, configuration: Record<string, unknown> }>) {
        if (!product.name) throw new Error("Name is required");

        // Auto-generate code if missing
        const code = product.code || product.name.toLowerCase().replace(/\s+/g, '_');

        const payload: Record<string, unknown> = {
            name: product.name,
            code: code,
            category: 'roof', // Default
            provider: 'Manual',
            updated_at: new Date()
        };

        if (product.description !== undefined) payload.description = product.description;
        if (product.image_url !== undefined) payload.image_url = product.image_url;
        if (product.standard_colors !== undefined) payload.standard_colors = product.standard_colors;
        if (product.custom_color_surcharge_percentage !== undefined) payload.custom_color_surcharge_percentage = product.custom_color_surcharge_percentage;
        if (product.configuration !== undefined) payload.configuration = product.configuration;

        if (product.id) {
            return supabase.from('product_definitions').update(payload).eq('id', product.id).select().single();
        } else {
            return supabase.from('product_definitions').insert(payload).select().single();
        }
    },

    /**
     * Get Product Image URL based on configuration
     */
    async getProductImage(modelId: string): Promise<string | undefined> {
        // Simple lookup from catalog for now
        // In future could query DB if images are variant-specific
        const models = catalogData.models as Array<{ id: string, image: string }>;
        const model = models.find(m => m.id.toLowerCase() === modelId.toLowerCase());
        return model?.image;
    },

    /**
     * Get Product Dimension Limits
     */
    async getProductLimits(modelId: string): Promise<{ minWidth: number, maxWidth: number, minDepth: number, maxDepth: number }> {
        const defaultLimits = { minWidth: 2000, maxWidth: 14000, minDepth: 2000, maxDepth: 6000 };

        try {
            // Run parallel queries for efficiency
            const [minW, maxW, minD, maxD] = await Promise.all([
                supabase.from('pricing_base').select('width_mm').eq('model_family', modelId).order('width_mm', { ascending: true }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('width_mm').eq('model_family', modelId).order('width_mm', { ascending: false }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('depth_mm').eq('model_family', modelId).order('depth_mm', { ascending: true }).limit(1).maybeSingle(),
                supabase.from('pricing_base').select('depth_mm').eq('model_family', modelId).order('depth_mm', { ascending: false }).limit(1).maybeSingle()
            ]);

            return {
                minWidth: minW.data?.width_mm || defaultLimits.minWidth,
                maxWidth: maxW.data?.width_mm || defaultLimits.maxWidth,
                minDepth: minD.data?.depth_mm || defaultLimits.minDepth,
                maxDepth: maxD.data?.depth_mm || defaultLimits.maxDepth
            };
        } catch (e) {
            console.error('Error fetching product limits:', e);
            return defaultLimits;
        }
    },

    /**
     * Exact Match Lookup for Base Price with Smart Fallback
     */
    async findBasePrice(criteria: {
        modelFamily: string;
        constructionType: 'wall' | 'free';
        coverType: string;
        zone: number;
        width: number;
        depth: number;
    }): Promise<{ price: number, variant_note?: string, properties?: { matchedWidth: number; matchedProjection: number; posts_count?: number; fields_count?: number } } | null> {
        console.log('🔍 Pricing Lookup:', criteria);

        // 1. Try Exact Match
        let exactQuery = supabase
            .from('pricing_base')
            .select('price_upe_net_eur, variant_note, posts_count, fields_count, width_mm, depth_mm')
            .ilike('model_family', criteria.modelFamily)
            .eq('construction_type', criteria.constructionType)
            .eq('zone', criteria.zone)
            .eq('width_mm', criteria.width)
            .eq('depth_mm', criteria.depth);

        // Flexible Cover Type Matching
        if (criteria.coverType.toLowerCase().includes('glass')) {
            exactQuery = exactQuery.ilike('cover_type', '%glass%');
        } else if (criteria.coverType.toLowerCase().includes('poly')) {
            exactQuery = exactQuery.ilike('cover_type', '%poly%');
        } else {
            exactQuery = exactQuery.ilike('cover_type', criteria.coverType);
        }

        const { data: exactData } = await exactQuery.maybeSingle();

        if (exactData) {
            console.log('✅ Exact Price Found:', exactData.price_upe_net_eur);
            return {
                price: exactData.price_upe_net_eur,
                variant_note: exactData.variant_note,
                properties: {
                    matchedWidth: exactData.width_mm,
                    matchedProjection: exactData.depth_mm,
                    posts_count: exactData.posts_count,
                    fields_count: exactData.fields_count
                }
            };
        }

        // 2. Smart Match (Next Larger)
        let smartQuery = supabase
            .from('pricing_base')
            .select('price_upe_net_eur, width_mm, depth_mm, variant_note, posts_count, fields_count')
            .ilike('model_family', criteria.modelFamily) // Case-insensitive Family match
            .eq('construction_type', criteria.constructionType)
            .eq('zone', criteria.zone) // Strict Zone match (safety)
            .gte('width_mm', criteria.width)
            .gte('depth_mm', criteria.depth);

        // Strict Cover Matching (Fixes Ambiguity between Opal/Clear)
        if (criteria.coverType) {
            smartQuery = smartQuery.ilike('cover_type', criteria.coverType);
        }

        const { data: smartData } = await smartQuery
            .order('width_mm', { ascending: true })
            .order('depth_mm', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (smartData) {
            console.log(`✅ Smart Match Found: Requested ${criteria.width}x${criteria.depth} -> Used ${smartData.width_mm}x${smartData.depth_mm}`);
            return {
                price: smartData.price_upe_net_eur,
                variant_note: smartData.variant_note,
                properties: {
                    matchedWidth: smartData.width_mm,
                    matchedProjection: smartData.depth_mm,
                    posts_count: smartData.posts_count,
                    fields_count: smartData.fields_count
                }
            };
        }

        console.warn('❌ Base Price Not Found. Attempting Manual Table Lookup...');

        // 3. Manual Table Lookup (Fallback for Raw Imports)
        // Check construction type: Surcharges rely on Base (Wall) + Surcharge.
        // If request is for 'free', we should return NULL here so the Service falls back to "Wall + Surcharge".
        // UNLESS the table explicitly says "Freestanding".
        const requestIsWall = criteria.constructionType === 'wall';

        const { data: manualTables } = await supabase
            .from('price_tables')
            .select('*')
            .ilike('name', `%${criteria.modelFamily}%`) as { data: { name: string; id: string; description?: string; attributes?: Record<string, any> }[] | null }; // Broad match on model name

        if (manualTables && manualTables.length > 0) {
            // Filter in JS for best match using Scoring System
            // We need to match criteria.zone and criteria.coverType

            // 1. Identify Target Keys
            const typeKey = criteria.coverType.includes('glass') ? 'Glass' : 'Poly';
            const zoneKey = `S${criteria.zone}`; // e.g. "S1"

            // Subtype Nuances
            const isRelax = criteria.coverType.includes('relax') || criteria.coverType.includes('gold') || criteria.coverType.includes('ir');
            const isOpal = criteria.coverType.includes('opal');
            const isClear = criteria.coverType.includes('clear') || (!isRelax && !isOpal);

            // 2. Score Tables
            let bestMatch: { name: string; id: string; description?: string } | null = null;
            let bestScore = -100;

            console.log(`🔎 Searching Manual Tables for: ${criteria.modelFamily} (${criteria.coverType}) Zone:${criteria.zone} Type:${criteria.constructionType}`);

            manualTables.forEach(t => {
                const name = t.name.toLowerCase();
                let score = 0;

                // A. Construction Type Check (Attribute Priority > Name Heuristic)
                const attrType = t.attributes?.installationType;

                if (attrType) {
                    // Strict Attribute Matching
                    if (attrType === 'freestanding' && requestIsWall) return; // Requested Wall, Table is Free -> Skip
                    if (attrType === 'wall-mounted' && !requestIsWall) return; // Requested Free, Table is Wall -> Skip
                } else {
                    // Legacy Name Matching (only if no attribute set)
                    const isExplicitFree = name.includes('freestanding') || name.includes('wolnostoj');
                    if (requestIsWall && isExplicitFree) return; // Disqualify
                    if (!requestIsWall && !isExplicitFree) return; // Disqualify
                }
                score += 10; // Construction type matches

                // B. Zone Check (Critical)
                // "Trendstyle - S1" matches "s1"
                // Also support "Zone 1" or "Z1"
                const hasZone = name.includes(` ${zoneKey.toLowerCase()}`) || name.includes(`-${zoneKey.toLowerCase()}`) || name.includes(`s${criteria.zone}`);
                if (!hasZone) return; // Disqualify (Zone mismatch is fatal usually)
                score += 10;

                // C. Material Check (High Priority)
                if (typeKey === 'Glass' && !name.includes('glass') && !name.includes('szkło')) {
                    // If searching for Glass but table doesn't say Glass, it might be Poly by default? 
                    // Or "Trendstyle - S1" is generic? Assuming generic is Poly usually.
                    // Score penalty if mismatch type
                }

                // D. Subtype Specifics (The IR Gold Fix)
                if (isRelax) {
                    if (name.includes('relax') || name.includes('ir') || name.includes('gold')) {
                        score += 50; // Huge boost for specific match
                    } else {
                        score -= 20; // Penalty for picking non-relax table when we want relax
                    }
                } else if (isOpal) {
                    if (name.includes('opal') || name.includes('mlecz')) {
                        score += 50;
                    } else {
                        score -= 10;
                    }
                } else if (isClear) {
                    // If we want clear, we prefer NOT to see "Relax" or "Opal"
                    if (name.includes('relax') || name.includes('gold') || name.includes('opal')) {
                        score -= 50; // Strong penalty: Don't pick a specialized table for clear
                    } else {
                        score += 10; // Neutral/Correct
                    }
                }

                // E. Tie Breaker for "Genric" vs "Specific" names?
                // Shorter names might be more generic.

                // console.log(`   ? Checking: ${t.name} -> Score: ${score}`);

                if (score > bestScore) {
                    bestScore = score;
                    bestMatch = t;
                }
            });

            const match = bestMatch;

            if (match && match.rows) {
                console.log(`✅ Selected Manual Table: ${match.name} (Score: ${bestScore})`);
                // Parse JSON Grid
                // rows: { width: number, ...projections: { [depth]: price } }
                const rows = match.rows as any[];

                // Sort by width
                const sortedRows = rows.sort((a, b) => a.width - b.width);

                // Find Row >= Width
                const row = sortedRows.find(r => r.width >= criteria.width);

                // ... (rest is same)
                if (row) {
                    // Check Projections in this row
                    // row = { width: 3000, "2000": 1500, "2500": 1600 ... }
                    // Find key >= depth
                    const depths = Object.keys(row).filter(k => k !== 'width' && !isNaN(Number(k))).map(Number).sort((a, b) => a - b);
                    const matchedDepth = depths.find(d => d >= criteria.depth);

                    if (matchedDepth) {
                        const price = Number(row[matchedDepth]);
                        if (price && !isNaN(price)) {
                            console.log(`✅ Manual Table Match: ${match.name} (W:${row.width} x D:${matchedDepth}) = ${price}`);
                            return {
                                price,
                                variant_note: 'Manual Table Price',
                                tableAttributes: match.attributes
                            };
                        }
                    }
                }
            }
        }

        return null; // Return null to indicate failure
    },

    /**
     * Main Calculation Function replacing legacy calculateOfferPrice
     */
    async calculateOfferPrice(
        product: ProductConfig,
        marginPercentage: number, // e.g. 0.30 for 30% MARGIN
        snowZone?: SnowZoneInfo,
        postalCode?: string
    ): Promise<PricingResult> {

        // 1. Normalize Inputs
        const constructionType = product.installationType === 'freestanding' ? 'free' : 'wall';

        let coverType = 'poly_clear'; // Default
        if (product.roofType === 'glass') {
            if (product.glassType === 'mat' || product.glassType === 'glass_opal') coverType = 'glass_opal';
            else if (product.glassType === 'sunscreen' || product.glassType === 'glass_tinted') coverType = 'glass_tinted';
            else coverType = 'glass_clear';
        } else {
            if (product.polycarbonateType === 'poly_opal') coverType = 'poly_opal';
            else if (['iq-relax', 'ir-gold', 'poly_iq_relax'].includes(product.polycarbonateType || '')) coverType = 'poly_iq_relax';
            else coverType = 'poly_clear';
        }

        // 1b. Fetch Global Settings (Parallel with other fetches if possible, but here is fine)
        // 1b. Fetch Global Settings (Parallel with other fetches if possible, but here is fine)
        let transportSettings: TransportSettings | undefined;
        let installationSettings: InstallationSettings | undefined;

        try {
            const [transport, installation] = await Promise.all([
                DatabaseService.getTransportSettings(),
                DatabaseService.getInstallationSettings()
            ]);
            transportSettings = transport;
            installationSettings = installation;
        } catch (e) {
            console.warn('Failed to fetch logistics settings', e);
        }

        // Snow Zone
        let zone = 1;
        if (snowZone && snowZone.id) {
            const parsed = parseInt(String(snowZone.id));
            if (!isNaN(parsed)) zone = parsed;
        }

        // 2. Lookup Base Price & Configuration
        let allDefData: any[] = [];
        try {
            // Fetch configuration AND custom color settings
            const { data, error } = await supabase
                .from('product_definitions')
                .select('id, configuration, code, custom_color_surcharge_percentage')
                .ilike('code', product.modelId);

            if (!error && data) allDefData = data;
        } catch (e) {
            console.warn('Configuration column likely missing, fetching without it');
            const { data } = await supabase
                .from('product_definitions')
                .select('id, code') // Fallback without new columns
                .ilike('code', product.modelId);
            if (data) allDefData = data;
        }

        // Find the "Best" record (Prioritize ones with configuration)
        let defData = (allDefData || []).sort((a: any, b: any) => {
            const hasConfigA = a.configuration && (a.configuration.freestanding_is_additive || (a.configuration.freestanding_surcharge_rules?.length > 0));
            const hasConfigB = b.configuration && (b.configuration.freestanding_is_additive || (b.configuration.freestanding_surcharge_rules?.length > 0));
            return (hasConfigB ? 1 : 0) - (hasConfigA ? 1 : 0);
        })[0];

        // FALLBACK: If no config on Product, check duplicate products OR Price Tables
        let productConfig = defData?.configuration || {};

        // If config is empty, check Price Tables (Legacy/Admin Store)
        if (!productConfig.freestanding_surcharge_rules) {
            console.log('🔄 Checking Price Tables for missing configuration (Smart Fallback)...');
            const { data: tableData } = await supabase
                .from('price_tables')
                .select('configuration, product:product_definitions!inner(code)')
                .eq('product.code', product.modelId) // Inner Join on Code
                .order('created_at', { ascending: false })
                .limit(1)
                .maybeSingle();

            if (tableData?.configuration) {
                console.log('✅ Found Configuration in Price Table via Code Match (Super Fallback)');
                productConfig = { ...productConfig, ...tableData.configuration };
            } else if (defData?.id) {
                const { data: simpleTable } = await supabase
                    .from('price_tables')
                    .select('configuration')
                    .eq('product_definition_id', defData.id)
                    .order('created_at', { ascending: false })
                    .limit(1)
                    .maybeSingle();
                if (simpleTable?.configuration) {
                    productConfig = { ...productConfig, ...simpleTable.configuration };
                }
            }
        }

        const isAdditive = productConfig.freestanding_is_additive === true;
        const useAdditiveLogic = isAdditive && constructionType === 'free';

        // 3. Find Base Price
        let priceResult = null;

        if (useAdditiveLogic) {
            console.log('⚡ Force Additive Logic for Freestanding (Configured)');
            priceResult = await this.findBasePrice({
                modelFamily: product.modelId,
                constructionType: 'wall', // Force Wall Lookup
                coverType,
                zone,
                width: product.width,
                depth: product.projection
            });
        } else {
            // Standard Lookup
            priceResult = await this.findBasePrice({
                modelFamily: product.modelId,
                constructionType,
                coverType,
                zone,
                width: product.width,
                depth: product.projection
            });
        }

        // --- NEW SURCHARGE LOGIC ---
        const surchargesBreakdown: { name: string; price: number }[] = [];
        let totalSurcharges = 0;

        // A. Freestanding Surcharge
        let freestandingSurcharge = 0;

        // Check for Explicit Freestanding Table
        const foundTableType = (priceResult as any)?.tableAttributes?.installationType;
        const isExplicitlyFreestanding = foundTableType === 'free' || foundTableType === 'freestanding';
        const isUniversalTable = foundTableType === 'all';

        // Apply Surcharge Logic (Corrected to avoid Double Counting)
        let shouldApplySurcharge = useAdditiveLogic;

        if (constructionType === 'free' && !shouldApplySurcharge) {
            if (!priceResult) {
                // No base price found for 'free'. We MUST try Wall + Surcharge.
                shouldApplySurcharge = true;
            } else {
                // We found a base price.
                // Only add surcharge if it's a Universal table (Base Price is Wall-like)
                // If foundTableType is undefined (Legacy), we assume it's CORRECT (Freestanding) because we queried structType='free'
                if (isUniversalTable) {
                    shouldApplySurcharge = true;
                }
            }
        }
        if (shouldApplySurcharge) {
            if (!useAdditiveLogic && !isUniversalTable) console.log('⚠️ Freestanding base price not found. Attempting Wall Base + Surcharge fallback.');
            if (isUniversalTable) console.log('⚡ Universal Table used for Freestanding. Applying Surcharge.');

            // If we don't have a price yet (Fallback case), try fetching Wall price

            // If we don't have a price yet (Fallback case), try fetching Wall price
            if (!priceResult) {
                priceResult = await this.findBasePrice({
                    modelFamily: product.modelId,
                    constructionType: 'wall', // Force Wall
                    coverType,
                    zone,
                    width: product.width,
                    depth: product.projection
                });
            }

            if (priceResult) {
                // Determine Surcharge Source
                const rules = defData?.configuration?.freestanding_surcharge_rules;

                if (rules && Array.isArray(rules) && rules.length > 0) {
                    // 1. Use Inline Configuration Rules (STRICT PRIORITY)
                    console.log('⚡ Using Configured Surcharge Rules');
                    const sorted = [...rules].sort((a: any, b: any) => a.max_width - b.max_width);
                    const match = sorted.find((r: any) => Number(r.max_width) >= product.width);

                    if (match) {
                        freestandingSurcharge = Number(match.price);
                        console.log(`⚡ Surcharge Applied: ${freestandingSurcharge} EUR (Limit: ${match.max_width}mm)`);
                    } else {
                        const maxRule = sorted[sorted.length - 1];
                        freestandingSurcharge = Number(maxRule.price);
                        console.warn(`⚠️ Width ${product.width} exceeds max rule (${maxRule.max_width}). Using max price: ${freestandingSurcharge}`);
                    }
                } else {
                    console.log('ℹ️ No freestanding rules found. Surcharge = 0.');
                    freestandingSurcharge = 0;
                }
            }
        }

        // Apply Freestanding Surcharge to Breakdown
        if (freestandingSurcharge > 0) {
            surchargesBreakdown.push({ name: 'Dopłata: Konstrukcja Wolnostojąca', price: freestandingSurcharge });
            totalSurcharges += freestandingSurcharge;
        }

        // B. Selected Surcharges (Glass, Options)
        if (product.selectedSurcharges && product.selectedSurcharges.length > 0) {
            for (const surchargeId of product.selectedSurcharges) {
                // We pass 'productConfig' (containing table rules) as override if needed, 
                // but getSurchargePrice mainly handles table rules via 4th arg.
                // We pass `productConfig` here as 4th arg to `getSurchargePrice`
                const surchargePrice = await this.getSurchargePrice(product.modelId, surchargeId, product.width, productConfig);
                if (surchargePrice > 0) {
                    // Try to format name nicely (since we don't have the explicit name from Meta here)
                    // or we could fetch it. Ideally, Service should return IDs and let UI map, but we promised a refactor.
                    // Simple prettify:
                    const prettyName = surchargeId
                        .replace(/_/g, ' ')
                        .replace(/\b\w/g, l => l.toUpperCase())
                        .replace('Glass ', 'Szkło ')
                        .replace('Poly ', 'Poliwęglan ');

                    surchargesBreakdown.push({ name: prettyName, price: surchargePrice });
                    totalSurcharges += surchargePrice;
                }
            }
        }

        // Base Price (Pure)
        const basePrice = priceResult?.price || 0;
        let runningTotal = basePrice + totalSurcharges;

        // C. Custom Color Surcharge (Percentage)
        if (product.customColor && defData?.custom_color_surcharge_percentage) {
            const colorSurcharge = runningTotal * (defData.custom_color_surcharge_percentage / 100);
            if (colorSurcharge > 0) {
                surchargesBreakdown.push({
                    name: `Kolor Niestandardowy (+${defData.custom_color_surcharge_percentage}%)`,
                    price: parseFloat(colorSurcharge.toFixed(2))
                });
                totalSurcharges += colorSurcharge;
                runningTotal += colorSurcharge;
            }
        }

        // D. Addons Total
        let addonsTotal = 0;
        (product.selectedAccessories || []).forEach(acc => {
            addonsTotal += (acc.price || 0) * (acc.quantity || 1);
        });

        // E. Custom Items
        let customItemsTotal = 0;
        (product.customItems || []).forEach(item => {
            customItemsTotal += (item.price || 0) * (item.quantity || 1);
        });

        // F. Installation & Logistics
        // Settings fetched at start of function (1b)

        const distance = calculateDistanceFromGubin(postalCode || '', transportSettings?.baseLocation);

        // Map to custom rates
        let customRates: InstallationDailyRates | null = null;
        if (installationSettings) {
            customRates = {
                day1: installationSettings.baseRatePerDay,
                day2: installationSettings.baseRatePerDay,
                day3: installationSettings.baseRatePerDay,
                additional: installationSettings.additionalDayRate || installationSettings.baseRatePerDay
            };
        }

        const installation = calculateInstallationCosts(
            product.installationDays ?? 0,
            distance || 0,
            transportSettings?.ratePerKm,
            customRates
        );

        // --- Final Calculation Logic (Fix: Services excluded from Margin) ---

        // 1. Product Cost (Base + Surcharges + Addons + Custom Items)
        // 2. Margin Logic (Applied to Product Only)
        // Fix: Distribute margin to components so UI Breakdown sums to Total
        const productTotal = basePrice + totalSurcharges + addonsTotal + customItemsTotal;

        const marginDecimal = marginPercentage > 1 ? marginPercentage / 100 : marginPercentage;
        const safeMargin = Math.min(Math.max(marginDecimal, 0), 0.99);
        const productSellingNet = productTotal / (1 - safeMargin);

        // 3. Service Costs (Pass-through / Net)
        // Installation and Travel are added directly to the NET price without margin markup
        const servicesTotal = (installation.dailyTotal || 0) + (installation.travelCost || 0);

        // 4. Final Totals
        let sellingPriceNet: number;
        let marginValue: number;

        if (product.isManual && product.manualPrice) {
            sellingPriceNet = product.manualPrice;
            marginValue = sellingPriceNet - (productTotal + servicesTotal);
        } else {
            sellingPriceNet = productSellingNet + servicesTotal;
            marginValue = productSellingNet - productTotal;
        }

        const sellingPriceGross = sellingPriceNet * 1.19;



        // Note: totalCost returned is usually for Reference. Here returns Selling Price Net to match UI.
        const dbPriceFound = priceResult !== null;
        const structuralNote = priceResult?.variant_note;

        return {
            basePrice: basePrice, // Raw Cost
            surchargesBreakdown, // Raw Cost
            addonsPrice: addonsTotal, // Raw Cost
            customItemsPrice: customItemsTotal, // Raw Cost

            totalCost: parseFloat((productTotal + servicesTotal).toFixed(2)), // Total Raw Cost (Materials + Services)
            marginPercentage: safeMargin * 100,
            marginValue,
            sellingPriceNet: parseFloat(sellingPriceNet.toFixed(2)),
            sellingPriceGross: parseFloat(sellingPriceGross.toFixed(2)),
            installationCosts: installation,

            _debuginfo: {
                found: dbPriceFound,
                info: `Model: ${product.modelId}, W:${product.width} D:${product.projection} Z:${zone}`
            },
            structuralNote,
            numberOfPosts: priceResult?.properties?.posts_count,
            numberOfFields: priceResult?.properties?.fields_count,
            matchedWidth: priceResult?.properties?.matchedWidth,
            matchedProjection: priceResult?.properties?.matchedProjection,
            constructionType
        };
    },


    /**
     * Fetch Matrix (All Rows) for Client-Side Filtering
     * Used by ProductConfigurator to find "Next Size Up" locally or get exact match details.
     */
    async getPriceMatrix(modelId: string, attributes: Record<string, string>) {
        console.log('Fetching Price Matrix for:', modelId, attributes);
        const zone = parseInt(attributes.snow_zone || '1');
        let constructionType = attributes.mounting === 'wall-mounted' ? 'wall' : (attributes.mounting || 'wall');
        if (constructionType === 'free') constructionType = 'freestanding';
        const coverTypeQuery = attributes.subtype || '';

        // Build query
        let query = supabase
            .from('pricing_base')
            .select('*')
            .ilike('model_family', modelId)
            .eq('zone', zone);

        // Initial filter removed to allow wildcard logic below to handle cover types correctly
        // (lines 685-687 removed)

        // Handle construction type if present in DB (some models might not have it?)
        // Assuming pricing_base has construction_type
        // Check for Additive Configuration
        const { data: defData } = await supabase
            .from('product_definitions')
            .select('configuration')
            .ilike('code', modelId)
            .maybeSingle();

        // Check for Additive Configuration or Presence of Surcharge Rules
        const config = defData?.configuration || {};
        const hasFreestandingRules = (config.free_standing_surcharge?.length > 0) || (config.freestanding_surcharge_rules?.length > 0);

        // If explicitly set to additive OR if we have rules defined, treat as additive.
        const isAdditive = config.freestanding_is_additive === true || hasFreestandingRules;

        if (constructionType) {
            // Smart Fallback Logic:
            // 1. We want to find Freestanding prices if they exist.
            // 2. But if they don't, and we have additive rules, we want Wall prices.
            // 3. Since we can't easily do "Try A else B" in one Supabase query specific to rows, 
            //    we will fetch BOTH types if needed, or rely on client filtering, or just use constructionType.

            // Wait, simply removing the "Force Wall" logic is start.
            // But we need to handle the fallback if Freestanding table doesn't exist.
            // Actually, getPriceMatrix returns ALL rows for the model/zone.
            // We can filter in JS? No, huge data? No, just one model/zone. It's small.
            // Let's remove the .eq('construction_type') filter from the query if we are in "Smart Mode",
            // or just fetch both 'wall' and 'freestanding' rows and decide in JS.

            // Current query: ilike model, eq zone.
            // Let's just fetch all construction types for this model/zone?
            // And filter in memory?
            // Usually < 100 rows per table. Safe.

            // Remove the explicit .eq construction_type filter unless we specifically want to narrow.
            // But verify performance? It's fine.
            // Actually, keep it simple: 
            // If checking for 'freestanding', we might get empty result if we restrict.
            // Let's fetch matching types.
            if (constructionType === 'free' || constructionType === 'freestanding') {
                // Fetch potentially both wall (for fallback) and freestanding (for primary)
                query = query.in('construction_type', ['wall', 'freestanding']);
            } else {
                query = query.eq('construction_type', constructionType);
            }
        }

        // Handle Cover Type with wildcards for generic types
        if (coverTypeQuery) {
            // If query is 'glass', match 'glass_clear', 'glass_opal', etc.
            // If query is 'polycarbonate', match 'poly_clear', 'poly_opal'
            if (coverTypeQuery.toLowerCase() === 'glass') {
                query = query.ilike('cover_type', '%glass%');
            } else if (coverTypeQuery.toLowerCase() === 'polycarbonate') {
                query = query.ilike('cover_type', '%poly%');
            } else {
                query = query.ilike('cover_type', `%${coverTypeQuery}%`);
            }
        }

        const { data, error } = await query;

        if (error) {
            console.error('Error fetching matrix:', error);
            return [];
        }
        return data || [];
    },

    /**
     * Find best match in the matrix for given dimensions.
     * Returns { total, variant_note, properties: { matchedWidth, matchedProjection } }
     */
    getDetailedPrice(matrix: any[], width: number, depth: number, preferredConstructionType?: string) {
        if (!matrix || matrix.length === 0) return { total: 0 };

        // 1. Try Exact or Best Match (Next Larger)
        // Sort by area (width*depth) ascending
        const sorted = [...matrix].sort((a, b) => {
            // Prioritize exact construction type if provided
            if (preferredConstructionType) {
                const aIsPref = a.construction_type === preferredConstructionType ? 1 : 0;
                const bIsPref = b.construction_type === preferredConstructionType ? 1 : 0;
                if (aIsPref !== bIsPref) return bIsPref - aIsPref; // Pref first
            }
            return (a.width_mm * a.depth_mm) - (b.width_mm * b.depth_mm);
        });

        // Find match: width >= requested AND depth >= requested
        const match = sorted.find(row => row.width_mm >= width && row.depth_mm >= depth);

        if (match) {
            return {
                total: match.price_upe_net_eur,
                variant_note: match.variant_note,
                construction_type: (match as any).construction_type, // Expose source type
                properties: {
                    matchedWidth: match.width_mm,
                    matchedProjection: match.depth_mm,
                    posts: match.posts,
                    fields: match.fields,
                    posts_count: match.posts_count,
                    fields_count: match.fields_count
                }
            };
        }

        return { total: 0 };
    },

    async getAvailableSurcharges(modelId: string, attributes: Record<string, string>) {
        if (!modelId) return [];

        try {
            // Get unique surcharge types available for this model family
            const { data, error } = await supabase
                .from('pricing_surcharges')
                .select('surcharge_type, price_eur')
                .ilike('model_family', modelId)
            // .eq('width_mm', 0) // Typically global surcharges might have width 0 or specific width?
            // Actually, surcharges vary by width. Use distinct on type to get NAMES.
            // But we need a price for display? Price might depend on width!
            // For UI "Option List", we just need the IDs/Names.
            // Let's get distinct types.
            // .order('surcharge_type');

            if (error) {
                console.error('Error fetching available surcharges:', error);
                return [];
            }

            // To get distinct types with a representative price (e.g. min price or just for listing)
            // Supabase distinct is tricky. Let's fetch all and dedupe in JS for now or use .rpc if needed.
            // Better: select distinct surcharge_type? simple .select() doesn't do distinct well without query modification.
            // Let's just return a static list of KNOWN surcharges if DB is complex, OR fetch all and unique.

            // Temporary robust approach: Fetch all for model, unique by type
            const unique = new Map();
            data?.forEach(item => {
                if (!unique.has(item.surcharge_type)) {
                    unique.set(item.surcharge_type, {
                        id: item.surcharge_type,
                        name: item.surcharge_type.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase()), // Prettify
                        price: item.price_eur // Just a sample price
                    });
                }
            });

            return Array.from(unique.values());

        } catch (e) {
            console.error('getAvailableSurcharges exception:', e);
            return [];
        }
    },

    async getAdditionalCosts(modelId: string, attributes: Record<string, string>) {
        return [];
    },

    async getTableConfig(modelId: string, attributes: Record<string, string>) {
        try {
            const product = await this.getMainProducts().then(products => products?.find(p => p.code === modelId));
            if (!product) return { config: {}, attributes: {} };

            // Find the active price table for this configuration
            const query = supabase
                .from('price_tables')
                .select('configuration, attributes')
                .eq('product_definition_id', product.id)
                .eq('is_active', true)
                .order('created_at', { ascending: false });

            // Apply filters based on attributes if possible
            // Note: price_tables uses JSONB variant_config, so filtering is tricky in simple query without knowing exact structure match.
            // But usually we can filter client side or use contains.

            // For now, fetch latest active for this product and check variant match client side or approximate.
            const { data } = await query;

            if (!data || data.length === 0) return { config: {}, attributes: {} };

            // Find best match in JS
            const snowZone = attributes.snow_zone || '1';
            const roofType = attributes.roof_type;
            const subtype = attributes.subtype;

            const match = data.find((t: any) => {
                // Soft match: if table has NO variant config, it's a fallback? Or strict?
                // Usually tables are specific.
                // We don't have access to variant_config here because I didn't select it.
                // I need to select it.
                return true; // Placeholder until I select variant_config
            });

            // Re-query with variant_config
            const { data: elaborateData } = await supabase
                .from('price_tables')
                .select('configuration, attributes, variant_config')
                .eq('product_definition_id', product.id)
                .eq('is_active', true)
                .order('created_at', { ascending: false });

            const exactMatch = elaborateData?.find((t: any) => {
                const vc = t.variant_config || {};
                // Check Zone
                if (vc.snowZone && String(vc.snowZone) !== String(snowZone)) return false;
                // Check Roof Type (if specified in table)
                if (vc.roofType && roofType && vc.roofType !== roofType) return false;
                // Check Subtype (if specified in table)
                if (vc.subtype && subtype && !subtype.includes(vc.subtype)) return false;
                // Note: Subtype matching might be broad.
                return true;
            });

            if (exactMatch) {
                return { config: exactMatch.configuration || {}, attributes: exactMatch.attributes || {} };
            }

            return { config: {}, attributes: {} };

        } catch (e) {
            console.error('getTableConfig error:', e);
            return { config: {}, attributes: {} };
        }
    },

    async calculateSurcharges(basePrice: number, width: number, depth: number, config: any, context: any): Promise<{ total: number, items: { name: string, price: number }[] }> {
        const items = [];
        let total = 0;

        // 1. IR Gold / Poly IQ Relax Handing
        // Check if polycarbonateType is set to 'poly_iq_relax'
        // context.roofType might be 'polycarbonate'. config object usually contains the full ProductConfig from UI.
        // But here 'config' arg is TABLE CONFIG.
        // checking 'context' which should contain user selections if passed correctly.
        // Wait, context in ProductConfigurator call (line 220) is { mountingType, roofType }. It doesn't have poly type.
        // I need to update ProductConfigurator to pass poly type in context OR use a specialized method.
        // Actually, let's keep it simple: Access 'config' if it WAS passed as user config? No, signature is (base, width, depth, tableConfig, context).
        // I need to change the signature or usage in ProductConfigurator?
        // ProductConfigurator calls it with:
        /*
          PricingService.calculateSurcharges(
              price,
              config.width,
              config.projection,
              tableConfig,
              {
                  mountingType: config.installationType === ...
                  roofType: config.roofType,
                  // ADD THIS:
                  polycarbonateType: config.polycarbonateType
              }
          )
        */

        if (context?.polycarbonateType === 'poly_iq_relax') {
            // Hardcoded check for "IR Gold" or "Poly IQ Relax" surcharge
            // We can check tableConfig for a price Override or just call getSurchargePrice
            // But getSurchargePrice is async. calculateSurcharges is currently sync?
            // No, it's defined as sync in the interface stub: calculateSurcharges(...): { ... }
            // But in my thought process I said "async". The stub is sync.
            // If I make it async, I need to await it in ProductConfigurator.
            // Let's make it async.
        }

        return { total, items };
    },

    async getSurchargePrice(modelFamily: string, surchargeType: string, width: number, configOverride?: any): Promise<number> {
        console.log(`💰 Surcharge Lookup: ${modelFamily} - ${surchargeType} (Width: ${width})`);

        // 0. Check Override (Propagated from Table Configuration)
        if (configOverride) {
            const rules = configOverride.free_standing_surcharge || configOverride.freestanding_surcharge_rules;
            if (surchargeType === 'freestanding' && rules && Array.isArray(rules) && rules.length > 0) {
                console.log('⚡ Found Freestanding Rules in Table Config Override');
                const sorted = [...rules].sort((a: any, b: any) => (a.width || a.max_width) - (b.width || b.max_width));
                const match = sorted.find((r: any) => Number(r.width || r.max_width) >= width);
                if (match) {
                    console.log(`✅ Rule Matched (Override): ${match.price} EUR`);
                    return Number(match.price);
                } else {
                    const maxRule = sorted[sorted.length - 1];
                    console.warn(`⚠️ Width ${width} exceeds max rule. Using max: ${maxRule.price}`);
                    return Number(maxRule.price);
                }
            }
        }

        // 1. Priority: Check Global Configuration Rules (product_definitions)
        if (surchargeType === 'freestanding') {
            const { data: defData } = await supabase
                .from('product_definitions')
                .select('configuration')
                .ilike('code', modelFamily)
                .maybeSingle();

            // Compatibility: Check both keys
            const rules = defData?.configuration?.free_standing_surcharge || defData?.configuration?.freestanding_surcharge_rules;
            if (rules && Array.isArray(rules) && rules.length > 0) {
                console.log('⚡ Found Freestanding Rules in Global Configuration');
                // SurchargeRulesModal saves as { width: number, price: number }
                // Sort by width ascending
                const sorted = [...rules].sort((a: any, b: any) => (a.width || a.max_width) - (b.width || b.max_width));

                // Find first rule that covers the width (Next Size Up)
                const match = sorted.find((r: any) => Number(r.width || r.max_width) >= width);

                if (match) {
                    console.log(`✅ Rule Matched: ${match.price} EUR (Limit: ${match.width || match.max_width}mm)`);
                    return Number(match.price);
                } else {
                    // Exceeds max rule - use largest
                    const maxRule = sorted[sorted.length - 1];
                    console.warn(`⚠️ Width ${width} exceeds max rule. Using max: ${maxRule.price}`);
                    return Number(maxRule.price);
                }
            }
        }

        // 2. Fallback: Legacy Table (pricing_surcharges)
        const { data } = await supabase
            .from('pricing_surcharges')
            .select('price_eur, width_mm')
            .eq('model_family', modelFamily)
            .eq('surcharge_type', surchargeType)
            .gte('width_mm', width)
            .order('width_mm', { ascending: true })
            .limit(1)
            .maybeSingle();

        if (data) {
            console.log(`✅ Surcharge Found (Legacy Table): ${data.price_eur} EUR (Matched Width: ${data.width_mm})`);
            return data.price_eur;
        }

        return 0;
    },

    calculateDiscountedPrice(price: number, discount: string) {
        return price;
    },

    // --- Legacy / Compatibility Stubs ---
    async checkPriceTableExists() { return true; },
    async getMatrixTables() { return []; },
    async getComponentLists() { return []; },

    async getAddonsByGroup(group: string) {
        try {
            const { data: addons } = await supabase.from('pricing_addons').select('*').eq('addon_group', group);

            if (!addons || addons.length === 0) return [];

            // Fetch metadata from product_components
            const keys = addons.map(a => a.addon_code).filter(k => k);
            const { data: meta } = await supabase
                .from('product_components')
                .select('component_key, image_url, description')
                .in('component_key', keys);

            // Map metadata
            const merged = addons.map(addon => {
                const info = meta?.find(m => m.component_key === addon.addon_code);
                return {
                    ...addon,
                    image_url: info?.image_url,
                    description: info?.description || addon.addon_name
                };
            });

            return merged;
        } catch (e) {
            console.error('Error fetching addons group:', group, e);
            return [];
        }
    }
};
